"""
Automated Email Dispatcher
==========================
Sends formatted executive stock research memos with attached PDF reports (Volume 1 & Volume 2) via SMTP.
"""

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from typing import Optional, Dict, Any, List
import logging

logger = logging.getLogger(__name__)


class EmailDispatcher:
    def __init__(
        self,
        smtp_host: str = "",
        smtp_port: int = 0,
        smtp_user: str = "",
        smtp_password: str = ""
    ):
        import os
        self.smtp_host = smtp_host or os.environ.get("SMTP_HOST", "smtp.gmail.com")
        self.smtp_port = smtp_port or int(os.environ.get("SMTP_PORT", 587))
        self.smtp_user = (smtp_user or os.environ.get("SMTP_USER", "shivamkumarrj15@gmail.com")).strip()
        self.smtp_password = (smtp_password or os.environ.get("SMTP_PASSWORD", "gpeskencryhmukad")).replace(" ", "").strip()

    def send_research_report(
        self,
        to_email: str,
        ticker: str,
        company_name: str,
        pdf_attachments: List[Dict[str, Any]],
        exec_summary: str,
        dcf_summary: Dict[str, Any],
        buffett_verdict: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """Sends research report email with attached PDF reports."""
        if not to_email or "@" not in to_email:
            return {"success": False, "error": "Invalid recipient email address"}

        msg = MIMEMultipart()
        msg["From"] = f"StockIQ Institutional Research <{self.smtp_user}>"
        msg["To"] = to_email
        msg["Subject"] = f"📊 Institutional Equity Research: {company_name} ({ticker}) [2-Volume Report & Buffett Verdict]"

        base_val = dcf_summary.get("base_case", {}).get("fair_value", "N/A")
        mos = dcf_summary.get("margin_of_safety_pct", "N/A")
        verdict = dcf_summary.get("valuation_verdict", "ANALYZE")
        
        bv = buffett_verdict or {}
        buff_stance = bv.get("verdict", "BUY_WITH_MARGIN_OF_SAFETY")
        buff_reasoning = bv.get("omaha_reasoning", "Satisfies value investing criteria if acquired with adequate margin of safety.")

        html_body = f"""
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            body {{ font-family: Arial, sans-serif; color: #1e293b; line-height: 1.6; }}
            .card {{ background: #f8fafc; border: 1px solid #cbd5e1; border-radius: 8px; padding: 18px; margin: 16px 0; }}
            .buffett-card {{ background: #fef3c7; border: 1.5px solid #d97706; border-radius: 8px; padding: 18px; margin: 16px 0; }}
            .badge {{ background: #059669; color: white; padding: 4px 10px; border-radius: 4px; font-weight: bold; font-size: 13px; }}
            .badge-buffett {{ background: #1e40af; color: white; padding: 5px 12px; border-radius: 4px; font-weight: bold; font-size: 14px; }}
            .highlight {{ color: #2563eb; font-weight: bold; }}
            .footer {{ font-size: 12px; color: #64748b; margin-top: 24px; border-top: 1px solid #e2e8f0; padding-top: 12px; }}
          </style>
        </head>
        <body>
          <h2>📈 Institutional Equity Research: {company_name} ({ticker})</h2>
          <p>Attached are <b>2 Comprehensive PDF Research Reports</b> prepared using the <b>Buffett & Munger 20-Stage Framework</b>.</p>
          
          <!-- Warren Buffett Verdict Box -->
          <div class="buffett-card">
            <h3 style="color: #92400e; margin-top:0;">🌟 WOULD WARREN BUFFETT BUY THIS STOCK?</h3>
            <p><b>FINAL VERDICT:</b> <span class="badge-buffett">{buff_stance}</span></p>
            <p><b>OMAHA EVALUATION:</b> {buff_reasoning}</p>
          </div>

          <!-- Executive Summary Card -->
          <div class="card">
            <h3>Executive Summary</h3>
            <p>{exec_summary}</p>
            <hr style="border: 0; border-top: 1px solid #e2e8f0;" />
            <p>
              <b>DCF Base Fair Value:</b> Rs. {base_val} &nbsp;|&nbsp; 
              <b>Margin of Safety:</b> {mos}% &nbsp;|&nbsp; 
              <b>Valuation Stance:</b> <span class="badge">{verdict}</span>
            </p>
          </div>

          <p><b>Attached Research Memos:</b></p>
          <ul>
            <li>📄 <b>Volume 1:</b> <i>Business Model & 9-Pillar Economic Moat</i> (Easy 1-minute breakdown, Value Chain, Sourcing, Unit Economics, Customers & Pricing Power).</li>
            <li>📄 <b>Volume 2:</b> <i>Financial Forensics & Buffett Decision Memo</i> (3-Scenario DCF, DuPont 3-Way ROE, Working Capital, Catalysts & Buffett 5-Gate Checklist).</li>
          </ul>

          <div class="footer">
            <p>Generated by <b>StockIQ Institutional AI Platform</b> • Strictly for research and educational purposes.</p>
          </div>
        </body>
        </html>
        """
        msg.attach(MIMEText(html_body, "html"))

        # Attach all PDFs
        for pdf_info in pdf_attachments:
            p_bytes = pdf_info.get("bytes")
            p_filename = pdf_info.get("filename", f"{ticker}_Report.pdf")
            if p_bytes:
                part = MIMEApplication(p_bytes, _subtype="pdf")
                part.add_header("Content-Disposition", "attachment", filename=p_filename)
                msg.attach(part)

        try:
            with smtplib.SMTP(self.smtp_host, self.smtp_port, timeout=15) as server:
                server.starttls()
                server.login(self.smtp_user, self.smtp_password)
                server.send_message(msg)
                logger.info(f"Research email successfully sent to {to_email}")
                return {"success": True, "recipient": to_email, "pdf_count": len(pdf_attachments)}
        except Exception as e:
            logger.error(f"Failed to send email to {to_email}: {e}")
            return {"success": False, "error": str(e), "recipient": to_email}
